# Generated by Django 5.1.6 on 2025-08-20 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_remove_note_file_note_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_app.language'),
        ),
        migrations.AddField(
            model_name='previouspaper',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_app.language'),
        ),
        migrations.AddField(
            model_name='semester',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_app.language'),
        ),
        migrations.AddField(
            model_name='subject',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_app.language'),
        ),
        migrations.AddField(
            model_name='unit',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_app.language'),
        ),
    ]
