# Generated by Django 5.1.6 on 2025-08-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_branch_language_previouspaper_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouspaper',
            name='language',
        ),
    ]
