# Generated by Django 5.1.6 on 2025-08-20 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_remove_previouspaper_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='note',
            name='uploaded_by',
        ),
    ]
