# Generated by Django 5.1.6 on 2025-08-20 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0006_remove_note_uploaded_at_remove_note_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='language',
        ),
    ]
