# Generated by Django 5.1.6 on 2025-08-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0007_remove_branch_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes_app.language'),
        ),
    ]
