# Generated by Django 5.1.6 on 2025-10-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0008_branch_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouspaper',
            name='file',
        ),
        migrations.AddField(
            model_name='previouspaper',
            name='pdf_url',
            field=models.URLField(blank=True, null=True, verbose_name='Cloudinary PDF URL'),
        ),
    ]
