# Generated by Django 5.1.6 on 2025-10-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0009_remove_previouspaper_file_previouspaper_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
